const newArray = new Array(0, 1, 2, 3, 4)
newArray.push(5)
console.log(newArray.slice(0))
newArray.push(6)
console.log(newArray)
newArray.pop()
console.log(newArray)
newArray.pop()
console.log(newArray)